spring:
  application:
    name: reservation-system
  datasource:
    url: jdbc:mysql://localhost:3306/reservation-system?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
