spring:
  application:
    name: reservation-system
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 300 # 5 minutes
  refresh-token-expiration: 604800 # 7 days
cors:
  allowed-origins: ${ALLOWED_ORIGINS}
reservation:
  max-duration: 12h